Repository prography/10th-5Team-BE, pull requests merged in 2025-08, with the labels that each got.

#150 Fix: 내 체험단 상태 조회 - 신청, 미신청 공고 기능 분리
  src/main/java/com/example/cherrydan/campaign/controller/CampaignStatusController.java
  src/main/java/com/example/cherrydan/campaign/repository/CampaignStatusRepository.java
  src/main/java/com/example/cherrydan/campaign/service/CampaignStatusService.java
  src/main/java/com/example/cherrydan/campaign/service/CampaignStatusServiceImpl.java
  src/main/java/com/example/cherrydan/common/exception/ErrorMessage.java
Labels: Fix

#157 fix: lazy loading error modified from fetchjoin
  src/main/java/com/example/cherrydan/activity/repository/ActivityAlertRepository.java
Labels: 🐛 fix, 🔧 patch

#161 Refactor: campaign dto update
  src/main/java/com/example/cherrydan/campaign/dto/BookmarkResponseDTO.java
  src/main/java/com/example/cherrydan/notice/domain/NoticeBanner.java
  src/main/java/com/example/cherrydan/notice/dto/NoticeBannerResponseDTO.java
  src/main/java/com/example/cherrydan/notice/repository/NoticeBannerRepository.java
  src/main/java/com/example/cherrydan/notice/service/NoticeBannerServiceImpl.java
Labels: 🔨 refactor

#162 feat: 캠페인 상태 배치 업데이트/삭제 기능을 구현했습니다
  src/main/java/com/example/cherrydan/campaign/controller/CampaignStatusController.java
  src/main/java/com/example/cherrydan/campaign/dto/CampaignStatusBatchRequestDTO.java
  src/main/java/com/example/cherrydan/campaign/dto/CampaignStatusDeleteRequestDTO.java
  src/main/java/com/example/cherrydan/campaign/dto/CampaignStatusRequestDTO.java
  src/main/java/com/example/cherrydan/campaign/service/CampaignStatusService.java
  src/main/java/com/example/cherrydan/campaign/service/CampaignStatusServiceImpl.java
  src/main/java/com/example/cherrydan/common/exception/ErrorMessage.java
  src/main/java/com/example/cherrydan/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/cherrydan/oauth/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/example/cherrydan/oauth/security/oauth2/exception/OAuth2AuthenticationProcessingException.java
Labels: 🔨 refactor

#166 refactor: 엔드포인트 수정
  src/main/java/com/example/cherrydan/campaign/controller/BookmarkController.java
Labels: 🔨 refactor
